backend = "glx";
vsync = true;
experimental-backend = false

opacity-rule = [
  "95:class_g = 'kitty'",
]

# Background blur
blur-method = "dual_kawase";
blur-strength = 5;

# Radius for window borders
corner-radius = 15
