backend = "glx";
vsync = true;
experimental-backend = false;

opacity-rule = [
  "95:class_g = 'kitty'",
];

# Background blur
blur-method = "dual_kawase";
blur-strength = 2;

# Radius for window borders
corner-radius = 14;

corner-radius-rules = [
  "0:class_g = 'polybar'",
  "0:class_g = 'Polybar'"
];

shadow-exclude = [
  "class_g = 'polybar'"
];
