backend = "glx";
vsync = true;
experimental-backend = false;

opacity-rule = [
  "95:class_g = 'kitty'",
  "100:class_g = 'i3'",
];

# Background blur
blur-method = "dual_kawase";
blur-background = true;
blur-strength = 2;

blur-background-exclude = [
  "class_g = 'Rofi'"
];

# Radius for window borders
corner-radius-rules = [
  "0:class_g = 'polybar'",
  "0:class_g = 'Polybar'",
  "0:class_g = 'Rofi'",
  "0:class_g = 'Dunst'",
  "0:class_g = 'dolphin'",
  "14:class_g = 'zen'"
];

shadow-exclude = [
  "class_g = 'i3'",
  "class_i = 'notification'",
  "class_g ?= 'Notification'",
  "name ~= 'notification'",
  "name ~= 'Notification'",
  "class_g = 'Polybar'"
];

