shell /usr/bin/fish

font_family       FiraCode Nerd Font
font_size         11.0
bold_font         auto
italic_font       auto
bold_italic_font  auto

# Background color
background #04070B

# General transparency
background_opacity 0.95
dynamic_background_opacity no

# Cursor
cursor_shape beam
cursor_thickness 2
cursor_blink_interval 0.5

# Disable beeps
enable_audio_bell no

# Reload kitty.conf
map ctrl+shift+f5 load_config_file
