"$schema" = "https://starship.rs/config-schema.json"
scan_timeout = 30
command_timeout = 1000
add_newline = false
follow_symlinks = false
palette = "custom"

format = """
 ⌁\
$directory\
${custom.giturl}\
$git_branch\
${custom.git_worktree}\
$git_status\
$character\
"""

right_format = """
$nodejs\
$python\
$rust\
$golang\
$java\
$cmd_duration\
"""

[directory]
style = "fg:ruddy"
format = "[ $path ]($style)"
truncation_length = 4

[line_break]
disabled = true

[character]
disabled = false
success_symbol = "[◈ ](bold fg:green)"
error_symbol = "[✖ ](bold fg:red)"
vimcmd_symbol = "[⦿ ](bold fg:yellow)"

[fill]
symbol = " "

[package]
disabled = true

[cmd_duration]
min_time = 2_000
format = "[⏱ $duration ](fg:mauve)"


[custom.giturl]
description = "Display symbol for remote Git server"
command = """
set GIT_REMOTE (git config --get remote.origin.url 2> /dev/null)
if string match -qr "github" -- $GIT_REMOTE
    echo "  "
else if string match -qr "gitlab" -- $GIT_REMOTE    
    echo "  "
else if string match -qr "bitbucket" -- $GIT_REMOTE
    echo "  "
else if string match -qr "git" -- $GIT_REMOTE
    echo " "
else
    echo " "
end
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
format = "$output"
require_repo = true
ignore_timeout = true

[git_branch]
symbol = "[](denim) "
style = "fg:cerulean bg:denim"
format = " on [$symbol$branch]($style)[](denim)"

[git_status]
format = "[$untracked$staged$modified$deleted$renamed$conflicted$ahead_behind ]($style)"
staged = "[ +${count}](green)"
modified = "[ !${count}](yellow)"
renamed = "[ »${count}](blue)"
deleted = "[ -${count}](red)"
untracked = "[ ?${count}](red)"
stashed = "[ ≡](cerulean)"
conflicted = "[ ✖${count}](red bold)"

ahead = "[⇡${count}](ruddy)"
behind = "[⇣${count}](aero)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](mauve)"

[custom.git_worktree]
description = "Show indicator when inside a git worktree"
shell = ["fish", "-c"]
command = """
if git rev-parse --git-dir >/dev/null 2>&1
      set common_dir (git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)
      set git_dir (git rev-parse --path-format=absolute --git-dir 2>/dev/null)
      if test "$common_dir" != "$git_dir"
            echo "⛓ "
      end
end
"""
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = " ([$output ]($style))"
style = "bold green"
require_repo = true
ignore_timeout = true

[nodejs]
symbol = ""
format = "[$symbol $version ]($style)"

[c]
symbol = " "
format = "[$symbol $version ]($style)"


[rust]
symbol = ""
format = "[$symbol $version ]($style)"

[golang]
symbol = ""
format = "[$symbol $version ]($style)"

[php]
symbol = ""
format = "[$symbol $version ]($style)"

[java]
symbol = " "
format = "[$symbol $version ]($style)"

[python]
symbol = ""
format = "[$symbol $version ]($style)"

[palettes.custom]
# Background
denim = "#151e3d"

# Foreground
ruddy = "#76abdf"

# Accent
cerulean = "#0492c2"
aero = "#c9ffe5"
mauve = "#cba6f7"
