[boot]
systemd = true

[user]
default = djacoz

[interop]
appendWindowsPath = false

[automount]
enabled = true
root = /mnt
options = "metadata,umask=22,fmask=11"

[network]
generateResolvConf = true
