;;====================================================
;;
;;  ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;; ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;; ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;; ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;; ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
;;  ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;;
;; ===================================================
;;                By JacobEscoto - 2026     
;; ===================================================
[color]

;; ===| MAIN COLORS |===
background     = #12151A
background-alt = #191D24
foreground     = #DCE0E5
muted          = #5D636F

;; ===| ICON COLORS |===
blue           = #73B3D4
cyan           = #96E0DD
red            = #D64950
green          = #0BDA51
lightgreen     = #77E687
lime           = #89F336
yellow         = #FCF55F
orange         = #D3B020
pink           = #FF69B4
purple         = #5D3FD3
indigo         = #4B0082
