;;====================================================
;;
;;  ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;; ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;; ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;; ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;; ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
;;  ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;;
;; ===================================================
;;                By JacobEscoto - 2026     
;; ===================================================
[color]
;; ===| MAIN COLORS |===
background     = #090B0D
foreground     = #E8E8E8
selected-bg    = #0F1114
muted          = #262626

;; ===| ACCENT COLORS |===
red = #D64950
