;;====================================================
;;
;;  ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;; ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;; ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;; ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;; ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
;;  ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;;
;; ===================================================
;;                By JacobEscoto - 2026     
;; ===================================================
[color]
;; ===| MAIN COLORS |===
background     = #11111b
foreground     = #CDD6F4
selected       = #181825
muted          = #585B70
muted-bright   = #A6ADC8

;; ===| ACCENT COLORS |===
red       = #E78284
green     = #A6E3A1
yellow    = #F9E2AF
lightblue = #89DCEB
peach     = #F5A97F
mauve     = #CBA6F7
