;; ===============================================
;;
;;  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
;; ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
;; ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
;; ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
;; ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
;;  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
;;
;; ===============================================
;;              By JacobEscoto - 2026
;; ===============================================

[global/wm]
margin-bottom = 0
margin-top = 0

;; File inclusion
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini

[bar/main]
monitor =
monitor-fallback =

wm-restack = i3
monitor-strict = false
override-redirect = false
bottom = false

fixed-center = true

width = 100%
height = 34

offset-x = 0%
offset-y = 0%

background = ${color.background}
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 0
line-color = ${color.background}

padding = 2

module-margin-left = 1
module-margin-right = 1


font-0 = "Iosevka Nerd Font:size=10;offset=0"
font-1 = "JetBrains Mono:size=11;offset=0"
font-2 = "Symbols Nerd Font Mono:size=12;offset=1"
font-3 = "feather:size=12;3"

modules-left = date separator
modules-center = i3
modules-right = battery network separator brightness pulseaudio separator powermenu

separator =
dim-value = 1.0

wm-name =

tray-position = none
tray-detached = false
tray-maxsize = 16

tray-background = ${color.background}

enable-ipc = true
