;; ===============================================
;;
;;  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
;; ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
;; ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
;; ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
;; ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
;;  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
;;
;; ===============================================
;;              By JacobEscoto - 2026
;; ===============================================

[global/wm]
margin-bottom = 0
margin-top = 0

;; File inclusion
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini

[bar/base]
height = 34
line-size = 2
padding-y = 4
radius = 10

background = ${color.background}
foreground = ${color.foreground}

font-0 = JetBrainsMono Nerd Font:pixelsize=11;2
font-1 = FiraCode Nerd Font:pixelsize=12;1

enable-ipc = true
override-redirect = true
wm-restack = i3

[bar/debian]
inherit = bar/base
width = 4%
offset-x = 1%
offset-y = 4px
modules-center = logo

[bar/left]
inherit = bar/base
width = 20%
offset-x = 6%
offset-y = 4px
modules-left = launcher separator i3

[bar/center]
inherit = bar/base
width = 15%
padding-left = 10
padding-right = 10
offset-x = 40%
offset-y = 4px
modules-center = datetime

module-margin-left = 1
module-margin-right = 1

[bar/right]
inherit = bar/base
width = 33%
offset-x = 66%
offset-y = 4px
padding-left = 2
modules-left = xkeyboard separator 
modules-center = network brightness audiomenu battery 
modules-right = powermenu

module-margin-left = 1
module-margin-right = 1
