;; ================================================================================================
;;
;; ██╗   ██╗███████╗███████╗██████╗   ███╗   ███╗ ██████╗ ██████╗ ██╗   ██╗██╗     ███████╗███████╗
;; ██║   ██║██╔════╝██╔════╝██╔══██╗  ████╗ ████║██╔═══██╗██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
;; ██║   ██║███████╗█████╗  ██████╔╝  ██╔████╔██║██║   ██║██║  ██║██║   ██║██║     █████╗  ███████╗
;; ██║   ██║╚════██║██╔══╝  ██╔══██╗  ██║╚██╔╝██║██║   ██║██║  ██║██║   ██║██║     ██╔══╝  ╚════██║
;; ╚██████╔╝███████║███████╗██║  ██║  ██║ ╚═╝ ██║╚██████╔╝██████╔╝╚██████╔╝███████╗███████╗███████║
;;  ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝
;;
;; ================================================================================================
;;                                    By JacobEscoto - 2026
;; ================================================================================================

[module/separator]
type = custom/text
content = |
content-foreground = ${color.muted}

;; -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:

[module/powermenu]
type = custom/text
content = 
content-foreground = ${color.lightgreen}

click-left = ~/.config/rofi/scripts/powermenu.sh &

;; -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:

;[module/terminal]
;type = custom/text
;content = 
;content-foreground = ${color.green}
;
;click-left = sensible-terminal --working-directory=$HOME &
;
;; -:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
