set -g mouse on
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -s escape-time 0
set -g history-limit 10000

set -g status-position top
set -g status-style bg=default,fg=colour242
set -g status-left ""
set -g status-right "#S "

setw -g window-status-current-style fg=white,bold
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[fg=white]#I:#W#[default] "

set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour242

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-Left' if-shell "$is_vim" 'send-keys C-Left' 'select-pane -L'
bind-key -n 'C-Down' if-shell "$is_vim" 'send-keys C-Down' 'select-pane -D'
bind-key -n 'C-Up' if-shell "$is_vim" 'send-keys C-Up' 'select-pane -U'
bind-key -n 'C-Right' if-shell "$is_vim" 'send-keys C-Right' 'select-pane -R'
